config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  post '/rate' => 'rater#create', :as => 'rate'
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :image, ImageUploader
  ratyrate_rateable "rating"
  validates_uniqueness_of :name, :scope => :author

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_filter :authenticate
  #
  # def authenticate
  #   redirect_to @users.sign_in
  # end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :require_permission, only: [:edit, :update, :destroy]
  # GET /books
  # GET /books.json

  def require_permission
    if current_user.admin?
    else
      redirect_to root_path
    end
  end

  def index
    @books = Book.all.reverse
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    if user_signed_in?
      @book = Book.new
    else
      respond_to do |format|
        format.html { redirect_to "/users/sign_in", notice: 'Please sign in'}
        format.json { render :show, status: :created, location: @user }
      end
    end
  end


  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :image)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col s8 offset-s2">
    <h1>Books</h1>
    <% if user_signed_in? %>
    <%= link_to 'New Book', new_book_path %>
    <% else %>
    <% end %>
      <% @books.each do |book| %>
        <div class="card">
          <div class="card-image">
            <%= image_tag book.image %>
          </div>
          <div class="card-action">
            <p> <%= book.name %> by <%= book.author %></p>
          </div>
          <div class="card-action">
            <p><%= rating_for book, 'rating', disable_after_rate: true %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<br>


</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @book.image.thumb.url %>
</p>

<p>
  <strong>Rating:</strong>
  <%= rating_for @book, 'rating', disable_after_rate: true %>
</p>

<% if current_user.try(:admin?) %>

<%= link_to 'Edit', edit_book_path(@book) %> |

<% else %>
<% end %>
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readinglist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<!-- <nav>
   <div class="nav-wrapper">
     <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Logo</a>
     <ul class="right hide-on-med-and-down">
       <% if user_signed_in? %>
         <li>
         <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
         </li>
       <% else %>
         <li>
         <%= link_to('Login', new_user_session_path)  %>
         </li>
       <% end %>
       <% if user_signed_in? %>
        <li>
          <%= link_to('Edit registration', edit_user_registration_path) %>
        </li>
        <% else %>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
        <% end %>
       <li><a href="sass.html"><i class="material-icons">search</i></a></li>
       <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
       <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
     </ul>
   </div>
 </nav> -->


<% if user_signed_in? %>
  <ul id="dropdown1" class="dropdown-content">
    <li>
      <%= link_to('Edit registration', edit_user_registration_path) %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
  </ul>
<% else %>
<% end %>


<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Gerty's List</a>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
      <% else %>
      <li>
        <%= link_to('Register', new_user_registration_path)  %>
      </li>
      <li>
        <%= link_to('Login', new_user_session_path) %>
      </li>
      <% end %>
     <!-- Dropdown Trigger -->
      <% if user_signed_in? %>
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Welcome <%= current_user.email %>!<i class="material-icons right">arrow_drop_down</i></a></li>
      <% else %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>